version: 2
updates:
  - package-ecosystem: gomod
    directory: /api
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: pip
    directory: /ai
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: docker
    directories:
      - /api
      - /ai
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci(deps)"
